In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder
from matplotlib import pyplot as plt

import torch
import torch.nn as nn
from pytorch_tabnet.tab_model import TabNetClassifier

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

train = pd.read_csv('..\\data\\UCI-fault\\Faults.csv',header=None)
pd.set_option('display.max_columns', None)
train.columns = ["X_Minimum", "X_Maximum", "Y_Minimum", "Y_Maximum", "Pixels_Areas", "X_Perimeter", "Y_Perimeter",
              "Sum_of_Luminosity", "Minimum_of_Luminosity", "Maximum_of_Luminosity", "Length_of_Conveyer", "TypeOfSteel_A300",
              "TypeOfSteel_A400", "Steel_Plate_Thickness", "Edges_Index", "Empty_Index", "Square_Index", "Outside_X_Index",
              "Edges_X_Index", "Edges_Y_Index", "Outside_Global_Index", "LogOfAreas", "Log_X_Index", "Log_Y_Index", "Orientation_Index",
              "Luminosity_Index", "SigmoidOfAreas", "Pastry", "Z_Scratch", "K_Scatch", "Stains", "Dirtiness", "Bumps", "Other_Faults" ]
train


X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0            42         50     270900     270944           267           17   
1           645        651    2538079    2538108           108           10   
2           829        835    1553913    1553931            71            8   
3           853        860     369370     369415           176           13   
4          1289       1306     498078     498335          2409           60   
...         ...        ...        ...        ...           ...          ...   
1936        249        277     325780     325796           273           54   
1937        144        175     340581     340598           287           44   
1938        145        174     386779     386794           292           40   
1939        137        170     422497     422528           419           97   
1940       1261       1281      87951      87967           103           26   

      Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0              44              24220                     76   
1              30              11397                     84   
2              19               7972                     99   
3              45              18996                     99   
4             260             246930                     37   
...           ...                ...                    ...   
1936           22              35033                    119   
1937           24              34599                    112   
1938           22              37572                    120   
1939           47              52715                    117   
1940           22              11682                    101   

      Maximum_of_Luminosity  Length_of_Conveyer  TypeOfSteel_A300  \
0                       108                1687                 1   
1                       123                1687                 1   
2                       125                1623                 1   
3                       126                1353                 0   
4                       126                1353                 0   
...                     ...                 ...               ...   
1936                    141                1360                 0   
1937                    133                1360                 0   
1938                    140                1360                 0   
1939                    140                1360                 0   
1940                    133                1360                 1   

      TypeOfSteel_A400  Steel_Plate_Thickness  Edges_Index  Empty_Index  \
0                    0                     80       0.0498       0.2415   
1                    0                     80       0.7647       0.3793   
2                    0                    100       0.9710       0.3426   
3                    1                    290       0.7287       0.4413   
4                    1                    185       0.0695       0.4486   
...                ...                    ...          ...          ...   
1936                 1                     40       0.3662       0.3906   
1937                 1                     40       0.2118       0.4554   
1938                 1                     40       0.2132       0.3287   
1939                 1                     40       0.2015       0.5904   
1940                 0                     80       0.1162       0.6781   

      Square_Index  Outside_X_Index  Edges_X_Index  Edges_Y_Index  \
0           0.1818           0.0047         0.4706         1.0000   
1           0.2069           0.0036         0.6000         0.9667   
2           0.3333           0.0037         0.7500         0.9474   
3           0.1556           0.0052         0.5385         1.0000   
4           0.0662           0.0126         0.2833         0.9885   
...            ...              ...            ...            ...   
1936        0.5714           0.0206         0.5185         0.7273   
1937        0.5484

In [3]:
'''
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(train)
'''

'\nfrom sklearn.preprocessing import MinMaxScaler\n\nscaler = MinMaxScaler()\nscaler.fit(train)\n'

In [4]:
y_value = pd.DataFrame(train, columns=["Pastry", "Z_Scratch", "K_Scatch", "Stains", "Dirtiness", "Bumps", "Other_Faults"])
x_value = pd.DataFrame(train, columns=["X_Minimum", "X_Maximum", "Y_Minimum", "Y_Maximum", "Pixels_Areas", "X_Perimeter", "Y_Perimeter",
              "Sum_of_Luminosity", "Minimum_of_Luminosity", "Maximum_of_Luminosity", "Length_of_Conveyer", "TypeOfSteel_A300",
              "TypeOfSteel_A400", "Steel_Plate_Thickness", "Edges_Index", "Empty_Index", "Square_Index", "Outside_X_Index",
              "Edges_X_Index", "Edges_Y_Index", "Outside_Global_Index", "LogOfAreas", "Log_X_Index", "Log_Y_Index", "Orientation_Index",
              "Luminosity_Index", "SigmoidOfAreas"])

#x, x_test, y, y_test = train_test_split(x_value,y_value, test_size=0.2, shuffle=True, random_state=1004)
#x_train, x_valid, y_train, y_valid = train_test_split(x,y, test_size=0.11, shuffle=True, random_state=1004)

tmp=[]
target_columns = ["Pastry", "Z_Scratch", "K_Scatch", "Stains", "Dirtiness", "Bumps", "Other_Faults"]
for i in range(len(y_value)):
    for j in range(0,7):
        if y_value.loc[i][j] == 1:
            tmp.append(target_columns[j])
            #tmp.append(j)

print(type(tmp[0]))
targets = pd.DataFrame(tmp,columns=["target"])
y_value=pd.DataFrame(tmp)
#x_value['target'] = tmp
#x_value
'''
y_value=[]
tmp=np.array(tmp)
print(tmp)
for i in tmp:
    y_value.append(i)
'''



<class 'str'>


'\ny_value=[]\ntmp=np.array(tmp)\nprint(tmp)\nfor i in tmp:\n    y_value.append(i)\n'

In [5]:

encoder=LabelEncoder()
for col in x_value.columns :
    x_value[col]=encoder.fit_transform(x_value[col].values)

x_value

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0            41         42        312        312           242           15   
1           430        455       1574       1575            94            8   
2           534        559       1157       1157            57            6   
3           546        572        399        399           160           11   
4           807        842        501        502           556           58   
...         ...        ...        ...        ...           ...          ...   
1936        212        240        361        361           247           52   
1937        136        153        378        378           259           42   
1938        137        152        412        412           264           38   
1939        131        148        446        446           337           94   
1940        790        824        100        100            89           24   

      Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0              43               1075                     66   
1              29                570                     74   
2              18                365                     89   
3              44                933                     89   
4             196               1532                     28   
...           ...                ...                    ...   
1936           21               1224                    109   
1937           23               1220                    102   
1938           21               1245                    110   
1939           46               1327                    107   
1940           21                595                     91   

      Maximum_of_Luminosity  Length_of_Conveyer  TypeOfSteel_A300  \
0                        25                  70                 1   
1                        40                  70                 1   
2                        42                  45                 1   
3                        43                  13                 0   
4                        43                  13                 0   
...                     ...                 ...               ...   
1936                     56                  17                 0   
1937                     50                  17                 0   
1938                     55                  17                 0   
1939                     55                  17                 0   
1940                     50                  17                 1   

      TypeOfSteel_A400  Steel_Plate_Thickness  Edges_Index  Empty_Index  \
0                    0                      5          112          127   
1                    0                      5         1155          471   
2                    0                      8         1373          368   
3                    1                     22         1108          710   
4                    1                     17          177          733   
...                ...                    ...          ...          ...   
1936                 1                      0          709          507   
1937                 1                      0          475          763   
1938                 1                      0          481          333   
1939                 1                      0          453         1164   
1940                 0                      5          286         1281   

      Square_Index  Outside_X_Index  Edges_X_Index  Edges_Y_Index  \
0              130               12            388            647   
1              158                6            507            582   
2              256                7            690            557   
3              111               17            435            647   
4               29               86            236            630   
...            ...              ...            ...            ...   
1936           520              150            418            439   
1937           507

In [6]:
x, x_test, y, y_test = train_test_split(x_value,y_value, test_size=0.1, shuffle=True, random_state=1004)
x_train, x_valid, y_train, y_valid = train_test_split(x,y, test_size=0.1, shuffle=True, random_state=1004)

x_train=x_train.to_numpy()
y_train = y_train.to_numpy()

x_test = x_test.to_numpy()
y_test = y_test.to_numpy()
x_valid = x_valid.to_numpy()
y_valid = y_valid.to_numpy()
'''
target = pd.DataFrame(tmp)
x, x_test, y, y_test = train_test_split(x_value,target, test_size=0.2, shuffle=True, random_state=1004)
x_train, x_valid, y_train, y_valid = train_test_split(x,y, test_size=0.11, shuffle=True, random_state=1004)

print(x_train)
'''
#y_train= np.array(y_train)
#y_valid= np.array(y_valid)
#y_test= np.array(y_test)


y_train = y_train.squeeze()
y_valid = y_valid.squeeze()
y_test = y_test.squeeze()

In [7]:
print(x_train)
print(x_train.shape)
print(type(x_train))

print(x_valid)
print(x_valid.shape)
print(type(x_valid))

print(x_test)
print(x_test.shape)
print(type(x_test))
print()
print()

print(y_train)
print(y_train.shape)
print(type(y_train))

print(y_valid)
print(y_valid.shape)
print(type(y_valid))

print(y_test)
print(y_test.shape)
print(type(y_test))

[[  58   68  868 ...  621  363  251]
 [ 313  331 1102 ...  411 1324    9]
 [   2    6 1576 ...  473   28   40]
 ...
 [  38  169 1506 ...  243  633  387]
 [  40  198  983 ...  321  924  387]
 [  52   67 1293 ...   60  579   61]]
(1571, 27)
<class 'numpy.ndarray'>
[[  40  172 1518 ...  473  954  387]
 [ 288  307  884 ...  710 1156  226]
 [ 549  576  255 ...  521 1511   35]
 ...
 [  40  197  612 ...  508 1155  387]
 [ 293  309  206 ...  661 1483  119]
 [ 503  537 1755 ...   76 1421   92]]
(175, 27)
<class 'numpy.ndarray'>
[[  83  103 1280 ...  368  287  331]
 [ 441  472  364 ...  395  367  225]
 [  40  195 1119 ...  136  437  387]
 ...
 [ 148  150  316 ...  807  342  321]
 [ 552  584  659 ...  496 1341  196]
 [ 828  856 1186 ...  818 1136  128]]
(195, 27)
<class 'numpy.ndarray'>


['Z_Scratch' 'Stains' 'Z_Scratch' ... 'K_Scatch' 'K_Scatch' 'Z_Scratch']
(1571,)
<class 'numpy.ndarray'>
['K_Scatch' 'Other_Faults' 'K_Scatch' 'Pastry' 'Dirtiness' 'Other_Faults'
 'Stains' 'K_Scatch' 'Other_Faul

In [8]:
cat_idxs = [8,9,10,11,12,13,20,22]
cat_dims = [161,100,84,2,2,24,3,183]

In [9]:
tabnet_params = {
                 "cat_emb_dim":1,
                 "optimizer_fn":torch.optim.Adam,
                 "optimizer_params":dict(lr=2e-2),
                 "scheduler_params":{"step_size":50, # how to use learning rate scheduler
                                 "gamma":0.9},
                 "scheduler_fn":torch.optim.lr_scheduler.StepLR,
                 "mask_type":'entmax' # "sparsemax"
                }

clf = TabNetClassifier(**tabnet_params
)

Device used : cuda


In [10]:
max_epochs = 100

# This illustrates the warm_start=False behaviour
#save_history = []

clf.fit(
        X_train=x_train, y_train=y_train,
        eval_set=[(x_train, y_train), (x_valid, y_valid)],
        eval_name=['train', 'valid'],
        eval_metric=['accuracy'],
        max_epochs=max_epochs , patience=20,
        batch_size=1024, virtual_batch_size=128,
        num_workers=0,
        weights=1,
        drop_last=False
    )
#save_history.append(clf.history["valid_auc"])
    
#assert(np.all(np.array(save_history[0]==np.array(save_history[1]))))

epoch 0  | loss: 2.79062 | train_accuracy: 0.08784 | valid_accuracy: 0.08    |  0:00:01s
epoch 1  | loss: 2.19894 | train_accuracy: 0.0732  | valid_accuracy: 0.08    |  0:00:01s
epoch 2  | loss: 1.91061 | train_accuracy: 0.07575 | valid_accuracy: 0.07429 |  0:00:01s
epoch 3  | loss: 1.70381 | train_accuracy: 0.08848 | valid_accuracy: 0.05714 |  0:00:01s
epoch 4  | loss: 1.5892  | train_accuracy: 0.09166 | valid_accuracy: 0.06857 |  0:00:01s
epoch 5  | loss: 1.5235  | train_accuracy: 0.13367 | valid_accuracy: 0.09714 |  0:00:02s
epoch 6  | loss: 1.44484 | train_accuracy: 0.14067 | valid_accuracy: 0.15429 |  0:00:02s
epoch 7  | loss: 1.37644 | train_accuracy: 0.15468 | valid_accuracy: 0.15429 |  0:00:02s
epoch 8  | loss: 1.27534 | train_accuracy: 0.16805 | valid_accuracy: 0.20571 |  0:00:02s
epoch 9  | loss: 1.18444 | train_accuracy: 0.18014 | valid_accuracy: 0.21714 |  0:00:02s
epoch 10 | loss: 1.13229 | train_accuracy: 0.18714 | valid_accuracy: 0.22857 |  0:00:02s
epoch 11 | loss: 1.09

In [12]:
x_test

array([[  83,  103, 1280, ...,  368,  287,  331],
       [ 441,  472,  364, ...,  395,  367,  225],
       [  40,  195, 1119, ...,  136,  437,  387],
       ...,
       [ 148,  150,  316, ...,  807,  342,  321],
       [ 552,  584,  659, ...,  496, 1341,  196],
       [ 828,  856, 1186, ...,  818, 1136,  128]], dtype=int64)

In [16]:
tab_preds = clf.predict_proba(x_test)

In [18]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
accuracy_score(y_test, tab_preds)

ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets

In [22]:
pred = np.clip(clf.predict(x_test), a_min=0, a_max=None)

UFuncTypeError: ufunc 'maximum' did not contain a loop with signature matching types (dtype('<U12'), dtype('int32')) -> None